using System;
using System.Collections.Generic;
using System.Text;

namespace Utilities
{
    /// <summary>
    /// This class provides message levels for the IMessage interface, and its implementations.
    /// </summary>
    public enum IMessageLevels
    {
        /// <summary>
        /// Only intended for use as a <see cref="IMessagePublisher.State"/> variable for <see cref="IMessagePublisher"/> objects with no errors.
        /// </summary>
        NoErrors = 0,
        /// <summary>
        /// This message level is reserved for non error messages.
        /// </summary>
        Message = 1,
        /// <summary>
        /// This message level is reserved for errors that will prevent data from being used in some future processes, but have not yet generated an exception.
        /// </summary>
        Error = 2,
        /// <summary>
        /// This message level is reserved for errors which are generated by an Exception.
        /// </summary>
        FatalError = 3,
    }
}
