
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace View.FrequencyRelationships
{
    /// <summary>
    /// Interaction logic for AnalyticalFrequencyEditor.xaml
    /// </summary>
    public partial class AnalyticalFrequencyEditor : UserControl
    {
        private bool _ClearChart = false;
        public AnalyticalFrequencyEditor()
        {
            InitializeComponent();
        }

        private void ValidationDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            //todo: Refactor: CO
            //FdaViewModel.FrequencyRelationships.AnalyticalFrequencyEditorVM vm = (FdaViewModel.FrequencyRelationships.AnalyticalFrequencyEditorVM)DataContext;
            //Type RowType = typeof(FdaViewModel.FrequencyRelationships.AnalyticalFrequencyRowItem);
            //System.Reflection.PropertyInfo propertyInfo = RowType.GetProperty(e.PropertyName);
            //object[] Attributes = propertyInfo.GetCustomAttributes(true);
            
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            _ClearChart = true;
            //Plot.InvalidatePlot();
        }
    }
}
