using System;
using FdaModel;
using FdaModel.Utilities.Attributes;

namespace FdaModel.Inputs.Functions.FrequencyFunctions
{
    [Author("John Kucharski", "06/10/2016", "08/22/2016")]
    public abstract class FrequencyFunction : BaseFunction
    {
        #region Notes
        /* 1. Need to add a ViewModel verification that the frequency function is monotonically increasing, otherwise the CreateOrdinatesFunctionFromInterval method will not work as intended. 
         * 2. Documentation for GetCDF function is confusing, and could affect functionality of CreateOrdinatesFunctionFromInterval, need to check to make sure its used correctly. */
        #endregion

        #region Fields
        protected Statistics.ContinuousDistribution _Function;
        #endregion

        #region Properties
        public virtual Statistics.ContinuousDistribution Function
        {
            get
            {
                return _Function;
            }
            set
            {
                _Function = value;
            }
        }
        #endregion

        #region Constructor
        [Tested(false)]
        /// <summary>
        /// Creates a new frequency function object. 
        /// </summary>
        /// <param name="functionPassedByChildren"> Function generated by the inherited class. </param>
        protected FrequencyFunction(ComputationPoint computationPoint, Statistics.ContinuousDistribution functionPassedByChildren, FunctionTypes functionType)
        {
            IndexPoint = computationPoint;
            Function = functionPassedByChildren;
            FunctionType = FunctionType;
        }
        #endregion

        #region Functions
        


        #endregion
    }
}
