name: Release

on:
  release:
    types: [ created ]

jobs:
  Build:
    runs-on: windows-latest      
    permissions:
        contents: write
    env:
      Solution_Name: Fda.sln                                  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3.2.0
      with:
          dotnet-version: '6.0.x'
      
    - name: Add Github and Nexus Source
      run:  |
        dotnet nuget add source --username HydrologicEngineeringCenter --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/HydrologicEngineeringCenter/index.json"
        dotnet nuget add source --name fda-nuget "https://www.hec.usace.army.mil/nexus/repository/fda-nuget/"
      
    - name: Install dependencies
      run: dotnet restore -v quiet
        
    - name: Build
      run: dotnet build -v quiet --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish -c Release -v quiet --no-build HEC.FDA.View/HEC.FDA.View.csproj
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: HEC-FDA-2.0-Snapshot
        path: .\build\publish\fda2.0

    - name: Zip
      run: 7z a HEC-FDA.7z D:\a\HEC-FDA\HEC-FDA\Build\publish\FDA2.0\ 

    - name: upload artifact to release
      uses: shogo82148/actions-upload-release-asset@v1.6.2
      with:
         upload_url: ${{ github.event.release.upload_url }}
         asset_path: HEC-FDA.7z
