name: Release

on:
  release:
    types: [ created ]

jobs:
  Build:
    runs-on: windows-latest      
    permissions:
        contents: read
    env:
      Solution_Name: Fda.sln                                  

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Source
      run: dotnet nuget add source --username HydrologicEngineeringCenter --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/HydrologicEngineeringCenter/index.json"

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
          GITHUB_TOKEN: ${{ github.token }}

    - name: Publish
      run: dotnet publish View/HEC.FDA.View.csproj

    - name: Zip
      run: 7z a HEC-FDA.7z D:\a\HEC-FDA\HEC-FDA\Build\publish\FDA2.0\

    - name: upload artifact to release
      uses: actions/upload-release-asset@v1
      env:
            GITHUB_TOKEN: ${{ github.token }}
      with:
         upload_url:  ${{ steps.get_release.outputs.upload_url }}
         asset_path: D:\a\HEC-FDA\HEC-FDA\Build\publish\HEC-FDA.7z
         asset_name: HEC-FDA.7z
         asset_content_type: application/zip
