name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  Project_Name: HEC.FDA.View/HEC.FDA.View.csproj
  dotnet-version: '9.0.x'

jobs:
  Build:
    runs-on: windows-latest                                      

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core SDK ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: ${{ env.dotnet-version }}

    - name: Create version number
      shell: pwsh
      run: |
        $TAG = $env:GITHUB_REF -replace 'refs/tags/', ''
        $VERSION = $TAG -replace '^v', ''
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV
      
    - name: Publish
      shell: pwsh
      run: |
        $PUBLISH_OUT = "${pwd}/TO-PACKAGE/"
        $DISTRIBUTION_FOLDER = "$PUBLISH_OUT/HEC-FDA-${{ env.VERSION }}/"
        echo "PUBLISH_OUT=$PUBLISH_OUT" >> $env:GITHUB_ENV
        dotnet publish -c Release -v quiet /p:Version=${{ env.VERSION }} -o $DISTRIBUTION_FOLDER ${{ env.PROJECT_NAME }} --self-contained true

    - name: Create Zip Archive
      shell: pwsh
      run: |
        $ZIP_OUT = "${pwd}/HEC-FDA-${{ env.VERSION }}.zip"
        echo "ZIP_OUT=$ZIP_OUT" >> $env:GITHUB_ENV
        Compress-Archive -Path "${{ env.PUBLISH_OUT }}/*" -DestinationPath $ZIP_OUT

    - name: Release
      uses: softprops/action-gh-release@v4
      with:
        files: ${{ env.ZIP_OUT }}
