name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  Project_Name: HEC.FDA.View/HEC.FDA.View.csproj

jobs:
  Build:
    runs-on: windows-latest                                      

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3.2.0
      with:
          dotnet-version: '8.0.x'
      
    - name: Add Github and Nexus Source
      run:  |
        dotnet nuget add source --username HydrologicEngineeringCenter --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/HydrologicEngineeringCenter/index.json"
        dotnet nuget add source --name fda-nuget "https://www.hec.usace.army.mil/nexus/repository/fda-nuget/"
        dotnet nuget add source --name dss "https://www.hec.usace.army.mil/nexus/repository/dss/"

    - name: Create version number
      shell: pwsh
      run: |
        $TAG = $env:GITHUB_REF -replace 'refs/tags/', ''
        $VERSION = $TAG -replace '^v', ''
        echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "The version is " + ${{ env.VERSION }}
      
    - name: Publish
      shell: pwsh
      run: |
        $PUBLISH_OUT = "${pwd}/TO-PACKAGE/"
        echo $PUBLISH_OUT >> $GITHUB_ENV
        dotnet publish -c Release -v quiet /p:Version=${{ env.VERSION }} -o $PUBLISH_OUT ${{ env.PROJECT_NAME }}
        echo "Published to " + ${{ env.PUBLISH_OUT }}

    - name: Zip Release Package
      shell: pwsh
      run: |
        $ZIP_OUT = "${pwd}/PACKAGED/HEC-FDA-${{ env.VERSION }}.zip"
        echo $ZIP_OUT >> $GITHUB_ENV
        Compress-Archive -Path ${{ env.PUBLISH_OUT }} -DestinationPath $ZIP_OUT
        echo "Compressed to " + ${{ env.ZIP_OUT }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: ${{ env.ZIP_OUT }}
